spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/${dbName}
    username: t1_homework
    password: t1_homework

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    open-in-view: false

  liquibase:
    enabled: true
    change-log: db/root-changelog.xml

  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:localhost:9092}
    producer:
      key-serializer: org.apache.kafka.common.serialization.LongSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
    consumer:
      group-id: task-notifier-group
      key-deserializer: org.apache.kafka.common.serialization.LongDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer


  mail:
    host: smtp.yandex.ru
    port: 587
    username: mentatge@yandex.ru
    password: ncdhomktywwyxijd
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
          ssl:
            trust: smtp.yandex.ru


notification:
  recipient: mentatge@yandex.ru

dbName: t1_homework_db

